apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins-service
    app: jenkins-deployment
spec:
  type: LoadBalancer
  ports:
    port: 8080
    targetPorts: 8080
  selector:
    name: jenkins-pod
    app: jenkins-deployment
    
