apiVersion: v1
kind: deployment
metadata:
	name: jenkins
	labels:
		name: jenkins
		app: jenkins

spec:
	replicas: 1
	selector:
		matchLabels:
			name: jenkins
			app: jenkins
			
	template:
		metadata:
			name: jenkins
			labels:
				name: jenkins
				app: jenkins

		spec:
			containers:
				- name: jenkins
				  image: jenkins
				  ports:
					- contanerPorts: 8080
